### ISSUE TITLE
Color data and what’s shown in the style-guide don’t line-up.

### ISSUE THREAD

**Issue by alloy** [artsy/elan#11]
It seems that the color data in [this file](https://github.com/artsy/elan/blob/ed10ac9a17cd1b4bc958652804efe665cd94e022/components/lib/variables/colors.json) doesn’t line-up with the colors shown [here](https://artsy-elan-production.herokuapp.com/colors). What gives?

**Comment by orta** [comment]
This needs a deploy - it's correct when running locally

![screen shot 2016-08-05 at 11 00 41 am](https://cloud.githubusercontent.com/assets/49038/17440751/e507ed6e-5afb-11e6-818e-e093d855a37b.png)

**Comment by orta** [comment]
Fixed

![screen shot 2016-08-05 at 11 23 16 am](https://cloud.githubusercontent.com/assets/49038/17441436/0e3c4dbc-5aff-11e6-9732-fb320bc1bedd.png)
