### ISSUE TITLE
What is a good way to let the mobile team know about changes to élan?

### ISSUE THREAD

**Issue by orta** [artsy/elan#4]
We now generate our colors based on https://github.com/artsy/Artsy-UIColors/pull/6 - how can I make it obvious to ping us when something has changed? ( I'm obviously watching this repo, but I get a _lot_ of github traffic )

**Comment by orta** [comment]
Danger is a good answer to this.

**Comment by orta** [comment]
:+1:

**Comment by dzucconi** [comment]
Deep dislike of having an entire Ruby dependency for this

**Comment by orta** [comment]
Hah - spoken like a true Javascript community member, I guess you're welcome to re-write Danger in JS.

**Comment by dzucconi** [comment]
Just trying to deploy this now and Heroku is choking on the build: `Gem::Ext::BuildError: ERROR: Failed to build gem native extension. ... ERROR: CMake is required to build Rugged` Ever see this one? I get it locally too.

**Comment by orta** [comment]
Oh yeah, grim, do a `bundle update danger` - I had to get rid of that dependency for that exact reason

**Comment by orta** [comment]
That will require changing `files_modified` to `modified_files` in the Dangerfile too
